<?php
/**
 * @category  Magento2.XX
 * @package   Sandeep_Crud
 * @author    Sandeep Gupta
 * @email ersandeepgu@gmail.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 */ 
?>
<?php $collection = $block->getCrudCollection(); ?>
<?php if($collection->count() > 0): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <table class="data table" id="crud-data-table">
        <caption class="table-caption">Sandeep Crud Data</caption>
        <thead>
            <tr>
                <th scope="col" class="col title">Full Name</th>
                <th scope="col" class="col sku">Email</th>
                <th scope="col" class="col sku">Telephone</th>
                <th scope="col" class="col sku">Dob</th>
                <th scope="col" class="col image">Image</th>
                <th scope="col" class="col sku">Experience</th>
                <th scope="col" class="col sku">Other Experience</th>
                <th scope="col" class="col created_at">Created At</th>
                <th scope="col" class="col actions">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $key => $data): ?>
                <tr>
                    <td data-th="fullname" class="col title"><?php echo $data->getFullname(); ?></td>
                    <td data-th="email" class="col sku"><?php echo $data->getEmail(); ?></td>
                    <td data-th="telephone" class="col sku"><?php echo $data->getTelephone(); ?></td>
                    <td data-th="Dob" class="col sku"><?php echo $data->getDob(); ?></td>
                    <td data-th="Image" class="col image">
                        <?php if($data->getImage()): ?>
                            <img width="70" height="70" src="<?php echo $block->getBaseUrl().'/media/'.$data->getImage(); ?>">
                        <?php else: ?>
                            <p>No Image</p>
                        <?php endif; ?>
                    </td>
                    <td data-th="Date" class="col created_at"><?php echo $data->getExperience(); ?></td>
                    <td data-th="Date" class="col created_at"><?php echo $data->getOtherexperience(); ?></td>
                    <td data-th="Date" class="col created_at"><?php echo $data->getCreatedAt(); ?></td>
                    <td data-th="Actions" class="col actions">
                        <?php $id = ($data->getCrudId()) ? $data->getCrudId() : $data['crud_id']; ?>
                        <!-- "$data->getTesting13Id()" was not working when I generated Vky_Testing13 module. That's why I had to place above line. -->
                        <a href="<?php echo $block->getBaseUrl().'crud/index/view/id/'.$id; ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>